name: Local
values:
  - key: baseUrl
    enabled: true
    value: 'http://localhost:8080'
  - key: accessToken
    enabled: true
    value: ''
  - key: refreshToken
    enabled: true
    value: ''
  - key: userId
    enabled: true
    value: ''
color: 180
